name: spring-dsl-integration-app
services:

  spring-dsl-integration:
    build: ..
    ports:
      - "18080:8080"
      - "18787:8787"
    restart: always
    depends_on:
      - broker
    environment:
      - SPRING_PROFILES_ACTIVE=docker
