version: '3.8'
services:

  camel-boot-integration:
    build: ..
    ports:
      - "18080:8080"
      - "18787:8787"
    restart: always
    depends_on:
      - broker
    environment:
      - SPRING_PROFILES_ACTIVE=docker
